const $=id=>document.getElementById(id);let sceneReady=false,currentView='garden';
function showView(view){if(!['garden','body','food','habitat','year'].includes(view))throw Error('Unbekannte Station');currentView=view;document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==view);document.querySelectorAll('nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.view===view));document.querySelectorAll('nav button[aria-current]').forEach(b=>b.setAttribute('aria-current','page'));if(view==='body'){if(!sceneReady)initModel();else window.dispatchEvent(new Event('resize'));}window.scrollTo(0,0);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function speak(){}
document.querySelectorAll('.read').forEach(b=>b.onclick=()=>speak(b.dataset.read));$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else{$('fullscreen').textContent='iPad bitte quer halten';}}catch{$('fullscreen').textContent='iPad bitte quer halten';}};
const parts=[['Stacheln','Die Stacheln schützen den Igel. Bei Gefahr kann er sich zu einer Kugel einrollen.'],['Schnauze','An der Schnauze sitzt die Nase. Mit ihr riecht der Igel und sucht nach Nahrung.'],['Augen','Die Augen des Igels sind klein.'],['Ohren','Mit seinen Ohren hört der Igel auch leise Geräusche.'],['Pfote mit Krallen','An jeder Pfote sitzen Krallen. Sie helfen dem Igel beim Graben.'],['Bauch','Am Bauch hat der Igel Fell und keine Stacheln.']];let practice=false,selected=null;const known=new Set();let hotButtons=[],hedgehog,homeRotation=.35;
parts.forEach(([name],i)=>{const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed','false');b.onclick=()=>{if(practice){selected=i;updateBody();}else{known.add(i);$('body-feedback').textContent=parts[i][1];speak(name);updateBody();}};$('words').append(b);});
function updateBody(){[...$('words').children].forEach((b,i)=>{b.setAttribute('aria-pressed',selected===i?'true':'false');b.classList.toggle('done',known.has(i));});hotButtons.forEach((b,i)=>{b.textContent=known.has(i)?parts[i][0]:String(i+1);b.classList.toggle('named',known.has(i));});$('discover').setAttribute('aria-pressed',String(!practice));$('practice').setAttribute('aria-pressed',String(practice));$('body-instruction').textContent=practice?'Wählt ein Wort. Tippt dann auf den passenden Punkt.':'Tippt auf einen Punkt am Igel.';}
function partClick(i){if(!practice){known.add(i);$('body-feedback').textContent=parts[i][1];speak(parts[i][0]);}else if(selected===null){$('body-feedback').textContent='Wählt zuerst ein Wort aus.';}else if(selected===i){known.add(i);selected=null;$('body-feedback').textContent=known.size===6?'Ihr habt alle Körperteile gefunden!':'Das passt! '+parts[i][1];speak(parts[i][0]);}else{$('body-feedback').textContent='Schaut noch einmal genau hin. Ihr könnt den Igel drehen.';}updateBody();}
function bodyReset(){known.clear();selected=null;$('body-feedback').textContent='Was fällt euch am Körper auf?';updateBody();}
$('discover').onclick=()=>{practice=false;bodyReset();};$('practice').onclick=()=>{practice=true;bodyReset();};$('restart-body').onclick=bodyReset;$('all-labels').onclick=()=>{parts.forEach((_,i)=>known.add(i));selected=null;$('body-feedback').textContent='Vergleicht: Wo sind Stacheln? Wo ist Fell?';updateBody();};
async function initModel(){sceneReady=true;try{
const T=await import('./three.module.js');const {createHedgehog}=await import('./hedgehog.js');const container=$('model');const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;container.append(renderer.domElement);
const scene=new T.Scene();const camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.set(3.7,2.4,6.7);camera.lookAt(0,.62,0);scene.add(new T.HemisphereLight(0xfff5e3,0x8b9285,2));const key=new T.DirectionalLight(0xfff0d9,3);key.position.set(1,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.bias=-.0005;scene.add(key);const fill=new T.DirectionalLight(0xe4ecf5,1.4);fill.position.set(-3,2,-4);scene.add(fill);
const animal=createHedgehog();hedgehog=animal.root;hedgehog.rotation.y=homeRotation;scene.add(hedgehog);const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.18}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;floor.receiveShadow=true;scene.add(floor);
const anchors=animal.anchors;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('model-leaders');svg.setAttribute('aria-hidden','true');container.append(svg);const lines=anchors.map(()=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');svg.append(line);return line;});
hotButtons=anchors.map((_,i)=>{const b=document.createElement('button');b.className='hotspot';b.setAttribute('aria-label','K\u00f6rperpunkt '+(i+1));b.onclick=()=>partClick(i);container.append(b);return b;});updateBody();let dragging=false,lastX=0,lastY=0;
renderer.domElement.onpointerdown=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!dragging)return;hedgehog.rotation.y+=(e.clientX-lastX)*.012;hedgehog.rotation.z=T.MathUtils.clamp(hedgehog.rotation.z+(e.clientY-lastY)*.004,-.6,.6);lastX=e.clientX;lastY=e.clientY;};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>dragging=false;
$('rotate-left').onclick=()=>hedgehog.rotation.y-=.5;$('rotate-right').onclick=()=>hedgehog.rotation.y+=.5;$('reset-model').onclick=()=>{hedgehog.rotation.set(0,homeRotation,0);};function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(w/h<1.2?4.2:3.7,2.4,w/h<1.2?8.7:6.7);camera.lookAt(0,.62,0);camera.updateProjectionMatrix();svg.setAttribute('viewBox','0 0 '+w+' '+h);}window.addEventListener('resize',resize);new ResizeObserver(resize).observe(container);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let lastFrame=0;function render(t){requestAnimationFrame(render);if(t-lastFrame<40)return;lastFrame=t;if(currentView!=='body')return;animal.tick(t*.001,reduced);hedgehog.updateMatrixWorld();const w=container.clientWidth,h=container.clientHeight;const offsets=[[-65,-30],[60,15],[72,-30],[20,-65],[35,53],[-68,47]];anchors.forEach((a,i)=>{const p=a.clone();hedgehog.localToWorld(p);p.project(camera);const x=(p.x+1)/2*w,y=(-p.y+1)/2*h;const bx=T.MathUtils.clamp(x+offsets[i][0],hotButtons[i].offsetWidth/2+8,w-hotButtons[i].offsetWidth/2-8);const by=T.MathUtils.clamp(y+offsets[i][1],38,h-30);hotButtons[i].style.left=bx+'px';hotButtons[i].style.top=by+'px';lines[i].setAttribute('x1',x);lines[i].setAttribute('y1',y);lines[i].setAttribute('x2',bx);lines[i].setAttribute('y2',by);});renderer.render(scene,camera);}requestAnimationFrame(render);
}catch(error){$('model-error').hidden=false;console.error(error);}}
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'open_learning_station',title:'Lernstation öffnen',description:'Öffnet Garten, Körper, Nahrung, Zuhause oder Igeljahr in der Igel-Forscherwelt.',inputSchema:{type:'object',properties:{station:{type:'string',enum:['garden','body','food','habitat','year']}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='station'))throw Error('Ungültige Eingabe');showView(input.station);return{station:currentView};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}

const field=$('catch-field'),item=$('catch-item'),igel=$('catch-igel');
const catchFoods=[['🪲','Käfer',true],['🪱','Regenwurm',true],['🐛','Raupe',true],['🍬','Bonbon',false],['🍦','Eis',false],['🍪','Keks',false]];
let running=false,paused=false,position=.5,fall=0,round=0,score=0,currentFood=null,lastTime=0,nextAt=0;
function moveIgel(x){position=Math.max(.08,Math.min(.92,x));igel.style.left=(position*100)+'%';}
function newItem(){currentFood=catchFoods[round%6];round++;fall=-65;item.innerHTML='<span aria-hidden="true">'+currentFood[0]+'</span><small>'+currentFood[1]+'</small>';item.style.left=([.22,.68,.45,.8,.32,.56][(round-1)%6]*100)+'%';item.hidden=false;}
function finish(){running=false;item.hidden=true;$('catch-pause').disabled=true;$('catch-start').textContent='Noch einmal spielen';$('catch-feedback').textContent='Runde geschafft! Ihr habt '+score+' Nahrungstiere gefangen. Was gehört zur Nahrung des Igels?';}
$('catch-start').onclick=()=>{running=true;paused=false;round=0;score=0;nextAt=0;lastTime=0;moveIgel(.5);$('catch-score').textContent='0 gefangen';$('catch-feedback').textContent='';$('catch-pause').disabled=false;$('catch-pause').textContent='Pause';$('catch-start').textContent='Neu starten';newItem();field.focus();};
$('catch-pause').onclick=()=>{paused=!paused;$('catch-pause').textContent=paused?'Weiter':'Pause';lastTime=0;};
field.onpointerdown=e=>{field.setPointerCapture(e.pointerId);moveIgel((e.clientX-field.getBoundingClientRect().left)/field.clientWidth);};
field.onpointermove=e=>{if(field.hasPointerCapture(e.pointerId))moveIgel((e.clientX-field.getBoundingClientRect().left)/field.clientWidth);};
field.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();moveIgel(position+(e.key==='ArrowLeft'?-.075:.075));}};
$('catch-left').onclick=()=>moveIgel(position-.12);$('catch-right').onclick=()=>moveIgel(position+.12);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused){paused=true;$('catch-pause').textContent='Weiter';}});
function catchTick(t){requestAnimationFrame(catchTick);if(!running||paused||currentView!=='food'){lastTime=0;return;}if(nextAt){if(t<nextAt)return;nextAt=0;if(round>=12){finish();return;}newItem();lastTime=t;}
const dt=lastTime?Math.min((t-lastTime)/1000,.05):0;lastTime=t;fall+=dt*75;item.style.top=fall+'px';
const bottom=field.clientHeight-92;if(fall>=bottom){const x=parseFloat(item.style.left)/100,hit=Math.abs(x-position)*field.clientWidth<58;item.hidden=true;if(hit&&currentFood[2]){score++;$('catch-feedback').textContent=currentFood[1]+': Das gehört zur Nahrung des Igels.';}else if(hit){$('catch-feedback').textContent=currentFood[1]+': Das ist keine geeignete Igelnahrung.';}else{$('catch-feedback').textContent='';}$('catch-score').textContent=score+' gefangen · '+round+'/12';nextAt=t+(hit?2200:700);}
}
requestAnimationFrame(catchTick);
const places=[['🍂','Laubhaufen',true,'Ein geschützter Laubhaufen bietet dem Igel ein Versteck. Im Winter kann er dort sein Nest bauen.'],['🌳','Dichte Hecke',true,'Unter einer dichten Hecke findet der Igel Schutz.'],['🪵','Reisighaufen',true,'Zwischen Ästen und Laub kann sich der Igel verstecken.'],['⚽','Offene Rasenfläche',false,'Hier fehlt ein geschütztes Versteck. Auf der Rasenfläche kann der Igel aber Nahrung suchen.'],['🚗','Straße',false,'Hier ist es gefährlich. Der Igel braucht geschützte Orte abseits des Verkehrs.'],['💧','Offener Teich',false,'Ein offener Teich ist kein Schlafplatz. Ein flacher Ausstieg hilft Tieren, wieder herauszukommen.']];
places.forEach(([icon,name,good,explanation])=>{const b=document.createElement('button');b.className='place';b.innerHTML='<span aria-hidden="true">'+icon+'</span><strong>'+name+'</strong>';b.onclick=()=>{b.classList.add('visited');b.setAttribute('aria-label',name+'. '+explanation);$('habitat-feedback').textContent=explanation;};$('habitat-places').append(b);});
$('habitat-reset').onclick=()=>{[...$('habitat-places').children].forEach((b,i)=>{b.classList.remove('visited');b.removeAttribute('aria-label');});$('habitat-feedback').textContent='Schaut genau hin und begründet eure Vermutung.';};
const seasons=['Frühling','Sommer','Herbst','Winter'],seasonIcons=['🌷','☀️','🍂','❄️'];
const activities=[['❄️','Der Igel hält Winterschlaf.',3],['🍂','Der Igel frisst sich Fettreserven an und sucht ein Winterquartier.',2],['🌷','Der Igel erwacht aus dem Winterschlaf und sucht Nahrung.',0],['🌙','In warmen Nächten sucht der Igel Nahrung. Viele Igel bekommen jetzt Junge.',1]];
let selectedCard=null;const assigned=new Set();
activities.forEach(([icon,label],i)=>{const b=document.createElement('button');b.className='year-card';b.innerHTML='<span aria-hidden="true">'+icon+'</span><span>'+label+'</span>';b.setAttribute('aria-pressed','false');b.onclick=()=>{if(assigned.has(i))return;selectedCard=i;[...$('year-cards').children].forEach((c,j)=>c.setAttribute('aria-pressed',String(j===i)));$('year-feedback').textContent='Welche Jahreszeit passt?';};$('year-cards').append(b);});
seasons.forEach((name,i)=>{const b=document.createElement('button');b.className='season';b.innerHTML='<span aria-hidden="true">'+seasonIcons[i]+'</span><strong>'+name+'</strong><div class="season-answer"></div>';b.onclick=()=>{if(selectedCard===null){$('year-feedback').textContent='Wählt zuerst eine Karte.';return;}const card=activities[selectedCard];if(card[2]!==i){$('year-feedback').textContent='Überlegt noch einmal: Welche Jahreszeit passt am besten?';return;}assigned.add(selectedCard);const c=$('year-cards').children[selectedCard];c.disabled=true;c.setAttribute('aria-pressed','false');b.querySelector('.season-answer').textContent=card[1];selectedCard=null;$('year-feedback').textContent=assigned.size===4?'Ihr habt das Igeljahr geordnet! Erzählt: Wie verändert sich das Leben des Igels?':'Das passt! Wählt die nächste Karte.';};$('year-seasons').append(b);});
$('year-reset').onclick=()=>{assigned.clear();selectedCard=null;[...$('year-cards').children].forEach(c=>{c.disabled=false;c.setAttribute('aria-pressed','false');});document.querySelectorAll('.season-answer').forEach(c=>c.textContent='');$('year-feedback').textContent='Was macht der Igel im Laufe des Jahres?';};
