const $=id=>document.getElementById(id);let sceneReady=false,currentView='garden';
function showView(view){if(!['garden','body','food'].includes(view))throw Error('Unbekannte Station');currentView=view;document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==view);document.querySelectorAll('nav button').forEach(b=>b.toggleAttribute('aria-current',b.dataset.view===view));document.querySelectorAll('nav button[aria-current]').forEach(b=>b.setAttribute('aria-current','page'));if(view==='body'){if(!sceneReady)initModel();else window.dispatchEvent(new Event('resize'));}window.scrollTo(0,0);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.88;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('de'));if(voice)u.voice=voice;speechSynthesis.speak(u);}
document.querySelectorAll('.read').forEach(b=>b.onclick=()=>speak(b.dataset.read));$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else{$('fullscreen').textContent='iPad bitte quer halten';}}catch{$('fullscreen').textContent='iPad bitte quer halten';}};
const parts=[['Stacheln','Die Stacheln schützen den Igel. Bei Gefahr kann er sich zu einer Kugel einrollen.'],['Nase','Mit seiner Nase sucht der Igel nach Nahrung.'],['Augen','Die Augen des Igels sind klein.'],['Ohren','Mit seinen Ohren hört der Igel auch leise Geräusche.'],['Beine','Der Igel hat vier kurze Beine.'],['Bauch','Am Bauch hat der Igel Fell und keine Stacheln.']];let practice=false,selected=null;const known=new Set();let hotButtons=[],hedgehog,homeRotation=.35;
parts.forEach(([name],i)=>{const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed','false');b.onclick=()=>{if(practice){selected=i;updateBody();}else{known.add(i);$('body-feedback').textContent=parts[i][1];speak(name);updateBody();}};$('words').append(b);});
function updateBody(){[...$('words').children].forEach((b,i)=>{b.setAttribute('aria-pressed',selected===i?'true':'false');b.classList.toggle('done',known.has(i));});hotButtons.forEach((b,i)=>{b.textContent=known.has(i)?parts[i][0]:String(i+1);b.classList.toggle('named',known.has(i));});$('discover').setAttribute('aria-pressed',String(!practice));$('practice').setAttribute('aria-pressed',String(practice));$('body-instruction').textContent=practice?'Wählt ein Wort. Tippt dann auf den passenden Punkt.':'Tippt auf einen Punkt am Igel.';}
function partClick(i){if(!practice){known.add(i);$('body-feedback').textContent=parts[i][1];speak(parts[i][0]);}else if(selected===null){$('body-feedback').textContent='Wählt zuerst ein Wort aus.';}else if(selected===i){known.add(i);selected=null;$('body-feedback').textContent=known.size===6?'Ihr habt alle Körperteile gefunden!':'Das passt! '+parts[i][1];speak(parts[i][0]);}else{$('body-feedback').textContent='Schaut noch einmal genau hin. Ihr könnt den Igel drehen.';}updateBody();}
function bodyReset(){known.clear();selected=null;$('body-feedback').textContent='Was fällt euch am Körper auf?';updateBody();}
$('discover').onclick=()=>{practice=false;bodyReset();};$('practice').onclick=()=>{practice=true;bodyReset();};$('restart-body').onclick=bodyReset;$('all-labels').onclick=()=>{parts.forEach((_,i)=>known.add(i));selected=null;$('body-feedback').textContent='Vergleicht: Wo sind Stacheln? Wo ist Fell?';updateBody();};
async function initModel(){sceneReady=true;try{
const T=await import('./three.module.js');const {createHedgehog}=await import('./hedgehog.js');const container=$('model');const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;container.append(renderer.domElement);
const scene=new T.Scene();const camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.set(3.7,2.4,6.7);camera.lookAt(0,.62,0);scene.add(new T.HemisphereLight(0xfff5e3,0x8b9285,2));const key=new T.DirectionalLight(0xfff0d9,3);key.position.set(1,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.bias=-.0005;scene.add(key);const fill=new T.DirectionalLight(0xe4ecf5,1.4);fill.position.set(-3,2,-4);scene.add(fill);
const animal=createHedgehog();hedgehog=animal.root;hedgehog.rotation.y=homeRotation;scene.add(hedgehog);const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.18}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;floor.receiveShadow=true;scene.add(floor);
const anchors=animal.anchors;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('model-leaders');svg.setAttribute('aria-hidden','true');container.append(svg);const lines=anchors.map(()=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');svg.append(line);return line;});
hotButtons=anchors.map((_,i)=>{const b=document.createElement('button');b.className='hotspot';b.setAttribute('aria-label','K\u00f6rperpunkt '+(i+1));b.onclick=()=>partClick(i);container.append(b);return b;});updateBody();let dragging=false,lastX=0,lastY=0;
renderer.domElement.onpointerdown=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!dragging)return;hedgehog.rotation.y+=(e.clientX-lastX)*.012;hedgehog.rotation.z=T.MathUtils.clamp(hedgehog.rotation.z+(e.clientY-lastY)*.004,-.6,.6);lastX=e.clientX;lastY=e.clientY;};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>dragging=false;
$('rotate-left').onclick=()=>hedgehog.rotation.y-=.5;$('rotate-right').onclick=()=>hedgehog.rotation.y+=.5;$('reset-model').onclick=()=>{hedgehog.rotation.set(0,homeRotation,0);};function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(w/h<1.2?4.2:3.7,2.4,w/h<1.2?8.7:6.7);camera.lookAt(0,.62,0);camera.updateProjectionMatrix();svg.setAttribute('viewBox','0 0 '+w+' '+h);}window.addEventListener('resize',resize);new ResizeObserver(resize).observe(container);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let lastFrame=0;function render(t){requestAnimationFrame(render);if(t-lastFrame<40)return;lastFrame=t;if(currentView!=='body')return;animal.tick(t*.001,reduced);hedgehog.updateMatrixWorld();const w=container.clientWidth,h=container.clientHeight;const offsets=[[-65,-30],[60,15],[72,-30],[20,-65],[35,53],[-68,47]];anchors.forEach((a,i)=>{const p=a.clone();hedgehog.localToWorld(p);p.project(camera);const x=(p.x+1)/2*w,y=(-p.y+1)/2*h;const bx=T.MathUtils.clamp(x+offsets[i][0],hotButtons[i].offsetWidth/2+8,w-hotButtons[i].offsetWidth/2-8);const by=T.MathUtils.clamp(y+offsets[i][1],38,h-30);hotButtons[i].style.left=bx+'px';hotButtons[i].style.top=by+'px';lines[i].setAttribute('x1',x);lines[i].setAttribute('y1',y);lines[i].setAttribute('x2',bx);lines[i].setAttribute('y2',by);});renderer.render(scene,camera);}requestAnimationFrame(render);
}catch(error){$('model-error').hidden=false;console.error(error);}}
const foods=[['🪲','Käfer',true,'Käfer gehören zur natürlichen Nahrung des Igels.'],['🪱','Regenwurm',true,'Der Igel frisst auch Regenwürmer.'],['🐛','Raupe',true,'Auch Raupen gehören zu seiner Nahrung.'],['🍎','Apfel',false,'Der Igel frisst kein Obst als typische Nahrung. Unter Fallobst sucht er nach kleinen Tieren.'],['🥛','Milch',false,'Milch ist für Igel ungeeignet und kann sie krank machen.'],['🍞','Brot',false,'Brot ist keine geeignete Nahrung für Igel.']];const chosen=new Set();let checked=false;foods.forEach(([emoji,label],i)=>{const b=document.createElement('button');b.className='food-card';b.setAttribute('aria-pressed','false');const icon=document.createElement('span');icon.className='emoji';icon.textContent=emoji;icon.setAttribute('aria-hidden','true');const name=document.createElement('span');name.textContent=label;b.append(icon,name);b.onclick=()=>{if(checked){speak(foods[i][3]);$('food-feedback').textContent=foods[i][3];return;}chosen.has(i)?chosen.delete(i):chosen.add(i);b.setAttribute('aria-pressed',String(chosen.has(i)));};$('food-grid').append(b);});
$('check-food').onclick=()=>{if(!chosen.size){$('food-feedback').textContent='Wählt zuerst aus: Was frisst der Igel?';return;}checked=true;let right=0;[...$('food-grid').children].forEach((b,i)=>{const correct=chosen.has(i)===foods[i][2];if(correct)right++;b.classList.add(correct?'correct':'wrong');b.setAttribute('aria-label',foods[i][1]+': '+foods[i][3]);});$('food-feedback').textContent=(right===6?'Alles richtig! ':'Schaut euch die Bilder noch einmal an. ')+'Igel fressen vor allem kleine Tiere. Tippt auf ein Bild und hört die Erklärung.';$('check-food').disabled=true;};$('reset-food').onclick=()=>{checked=false;chosen.clear();[...$('food-grid').children].forEach(b=>{b.classList.remove('correct','wrong');b.setAttribute('aria-pressed','false');b.removeAttribute('aria-label');});$('food-feedback').textContent='Erst vermuten. Dann gemeinsam prüfen.';$('check-food').disabled=false;};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'open_learning_station',title:'Lernstation öffnen',description:'Öffnet Garten, Körper oder Nahrung in der Igel-Forscherwelt.',inputSchema:{type:'object',properties:{station:{type:'string',enum:['garden','body','food']}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='station'))throw Error('Ungültige Eingabe');showView(input.station);return{station:currentView};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}
