import * as T from './three.module.js';
export function createHedgehog(){
 const root=new T.Group(),head=new T.Group();root.add(head);let seed=173;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const material=(c,roughness=.9)=>new T.MeshStandardMaterial({color:c,roughness});
 const coat=material(0x6c5b4c), skin=material(0x6d5546),noseMat=material(0x211c1a,.28), eyeMat=material(0x0b0908,.08);
 const sphere=new T.SphereGeometry(1,32,24);
 function oval(group,pos,scale,mat){const m=new T.Mesh(sphere,mat);m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
 // Continuous pear-shaped torso, low on its short feet.
 function bodyPoint(n){const x=-.4+n.x*1.35;const taper=1-.16*Math.max(n.x,0);return new T.Vector3(x,.66+n.y*.83*taper,n.z*.79*taper);}
 const bodyGeo=new T.SphereGeometry(1,64,40);const bp=bodyGeo.attributes.position;const bcolors=[];for(let i=0;i<bp.count;i++){const n=new T.Vector3().fromBufferAttribute(bp,i);const p=bodyPoint(n);bp.setXYZ(i,p.x,p.y,p.z);const c=new T.Color().setHSL(.08,.17,.25+random()*.085);bcolors.push(c.r,c.g,c.b);}bodyGeo.setAttribute('color',new T.Float32BufferAttribute(bcolors,3));bodyGeo.computeVertexNormals();const body=new T.Mesh(bodyGeo,new T.MeshStandardMaterial({vertexColors:true,roughness:1}));body.castShadow=true;root.add(body);
 // Fine banded tapered quills, instanced for efficient rendering on an iPad.
 const quillGeo=new T.CylinderGeometry(.001,.013,1,5,6);quillGeo.translate(0,.5,0);const qp=quillGeo.attributes.position;const qc=[];for(let i=0;i<qp.count;i++){const y=qp.getY(i);const c=new T.Color(y>.87?0xe8dbb8:y>.65?0x44352a:y>.48?0xc5b58f:y>.12?0x403228:0x99866b);qc.push(c.r,c.g,c.b);}quillGeo.setAttribute('color',new T.Float32BufferAttribute(qc,3));const quillMat=new T.MeshStandardMaterial({vertexColors:true,roughness:.87});const quills=new T.InstancedMesh(quillGeo,quillMat,7200);quills.castShadow=false;quills.receiveShadow=true;const dummy=new T.Object3D();let qi=0;for(let i=0;i<12500&&qi<7200;i++){const u=(i+.5)/12500;const phi=i*2.39996323;const yy=1-2*u;const r=Math.sqrt(1-yy*yy);const n=new T.Vector3(Math.cos(phi)*r,yy,Math.sin(phi)*r);if(n.y<-.37||n.x>.81)continue;const p=bodyPoint(n);p.addScaledVector(n,-.025);const direction=new T.Vector3(n.x/1.35,n.y/.83,n.z/.79).normalize();direction.x-=.48+random()*.2;direction.y+=.07;direction.z+=(random()-.5)*.17;direction.normalize();dummy.position.copy(p);dummy.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction);const length=.16+random()*.14;dummy.scale.set(.65+random()*.65,length,.65+random()*.65);dummy.updateMatrix();quills.setMatrixAt(qi++,dummy.matrix);}quills.count=qi;root.add(quills);
 // One smoothly tapering head, with no cone seam at the muzzle.
 const rings=[ [.5,.61,.37,.39],[.65,.61,.40,.39],[.86,.57,.39,.35],[1.07,.5,.32,.29],[1.27,.42,.25,.23],[1.46,.34,.18,.17],[1.63,.29,.12,.12],[1.73,.28,.075,.075] ];const hp=[],indices=[],hc=[];const sides=48;for(let j=0;j<rings.length;j++){const [x,y,ry,rz]=rings[j];for(let k=0;k<sides;k++){const a=k/sides*Math.PI*2;const z=Math.sin(a)*rz;hp.push(x,y+Math.cos(a)*ry,z);const top=Math.cos(a);const color=new T.Color().setHSL(.079,.18,(top>.1?.43:.34)+random()*.045-j*.013);hc.push(color.r,color.g,color.b);if(j){const prev=(j-1)*sides+k,cur=j*sides+k,next=(k+1)%sides;indices.push(prev,(j-1)*sides+next,cur,cur,(j-1)*sides+next,j*sides+next);}}}const headGeo=new T.BufferGeometry();headGeo.setAttribute('position',new T.Float32BufferAttribute(hp,3));headGeo.setAttribute('color',new T.Float32BufferAttribute(hc,3));headGeo.setIndex(indices);headGeo.computeVertexNormals();const headMesh=new T.Mesh(headGeo,new T.MeshStandardMaterial({vertexColors:true,roughness:1,side:T.DoubleSide}));headMesh.castShadow=true;head.add(headMesh);
 const nose=oval(head,[1.755,.285,0],[.095,.068,.108],noseMat);for(const z of [-.066,.066])oval(head,[1.821,.302,z],[.018,.013,.013],eyeMat);
 const eyes=[];for(const side of [-1,1]){const eye=oval(head,[1.12,.615,side*.267],[.052,.051,.026],eyeMat);eye.rotation.y=side*.23;eyes.push(eye);oval(head,[1.128,.633,side*.288],[.011,.012,.007],material(0xece4ce,.1));
 // Small rounded ears nestle against the quill edge.
 const ear=oval(head,[.67,.84,side*.345],[.13,.166,.062],coat);ear.rotation.x=side*.32;const inner=oval(head,[.687,.852,side*.392],[.088,.116,.017],skin);inner.rotation.x=side*.32;}
 const legGroups=[];for(const x of [-1.05,.53])for(const side of [-1,1]){const leg=new T.Group();root.add(leg);leg.position.set(x,.17,side*.47);oval(leg,[0,0,0],[.13,.26,.13],coat);oval(leg,[.08,-.11,side*.055],[.195,.085,.12],skin);for(let k=0;k<5;k++){const z=(k-2)*.045+side*.055;oval(leg,[.225,-.105,z],[.06,.035,.029],skin);const claw=new T.Mesh(new T.ConeGeometry(.014,.085,6),material(0xaca08a));claw.rotation.z=-Math.PI/2;claw.position.set(.291,-.106,z);claw.castShadow=true;leg.add(claw);}legGroups.push(leg);}
 // Short coarse fur follows the face and exposed lower sides.
 const hairGeo=new T.CylinderGeometry(.0006,.0025,1,3);hairGeo.translate(0,.5,0);const hairMat=new T.MeshStandardMaterial({color:0x9b8a72,roughness:1});const hairs=new T.InstancedMesh(hairGeo,hairMat,6800);const headHairs=new T.InstancedMesh(hairGeo,hairMat,3800);let bi=0;for(let i=0;i<13000&&bi<6800;i++){const n=new T.Vector3(random()*2-1,random()*2-1,random()*2-1).normalize();if(n.y>.06||n.y<-.94)continue;dummy.position.copy(bodyPoint(n));const d=n.clone();d.x-=.2;d.normalize();dummy.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d);dummy.scale.set(1,.04+random()*.055,1);dummy.updateMatrix();hairs.setMatrixAt(bi++,dummy.matrix);const c=new T.Color().setHSL(.083,.15,.27+random()*.22);hairs.setColorAt(bi-1,c);}hairs.count=bi;root.add(hairs);for(let i=0;i<3800;i++){const j=Math.floor(random()*6);const t=random();const a=random()*Math.PI*2;const r0=rings[j],r1=rings[j+1];const x=T.MathUtils.lerp(r0[0],r1[0],t),y=T.MathUtils.lerp(r0[1],r1[1],t),ry=T.MathUtils.lerp(r0[2],r1[2],t),rz=T.MathUtils.lerp(r0[3],r1[3],t);dummy.position.set(x,y+Math.cos(a)*ry,Math.sin(a)*rz);const dir=new T.Vector3(-.5,Math.cos(a),Math.sin(a)).normalize();dummy.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir);dummy.scale.set(1,.025+random()*.04,1);dummy.updateMatrix();headHairs.setMatrixAt(i,dummy.matrix);headHairs.setColorAt(i,new T.Color().setHSL(.078,.16,.32+random()*.25));}head.add(headHairs);
 // Sparse whiskers extend from the muzzle, rather than a cartoon moustache.
 const whiskerPos=[];for(const side of [-1,1])for(let i=0;i<7;i++){const x=1.4+random()*.18,y=.31+(random()-.5)*.08,z=side*.14;whiskerPos.push(x,y,z,x-.1-random()*.18,y+(random()-.5)*.2,z+side*(.22+random()*.16));}const wg=new T.BufferGeometry();wg.setAttribute('position',new T.Float32BufferAttribute(whiskerPos,3));head.add(new T.LineSegments(wg,new T.LineBasicMaterial({color:0x554c42,transparent:true,opacity:.65})));
 const anchors=[new T.Vector3(-.5,1.63,.12),new T.Vector3(1.84,.29,0),new T.Vector3(1.12,.615,.295),new T.Vector3(.69,.96,.4),new T.Vector3(.69,.07,.6),new T.Vector3(-.2,.14,.68)];
 return {root,anchors,tick(seconds,reduced){if(reduced)return;body.scale.y=1+Math.sin(seconds*2)*.003;head.rotation.y=Math.sin(seconds*.85)*.018;const blink=Math.pow(Math.max(0,Math.sin(seconds*.67)),36);eyes.forEach(e=>e.scale.y=.051*(1-blink*.88));}};
}
